name: Agent Tools

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semantic version to use to generate a new release'
        required: true
        type: string
      author:
        description: 'The author of the release'
        required: true
        type: string

jobs:
  docker-publish-tools:
    runs-on: ubuntu-latest
    name: Docker Publish Agent Tools
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/dist/CHANGELOG.txt
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ env.GIT_TAG }}
          repository: hoophq/hoopcli
        env:
          GIT_TAG: ${{ env.GIT_TAG }}